### ISSUE TITLE
Organizzazione file progetto

### ISSUE THREAD

**Issue by leicaflorian** [marius-leica/udemy#1]
I file all'interno del progetto vanno divisi meglio in sottocartelle.
Ad esempio sarebbe meglio creare una cartella che solitamente si chiama "assets" dove inserire le immagini, invece di inserirle nella "root folder", quindi cartella principale.

Ad esempio la struttura potrebbe essere:

```
root
  |- styles/
       |- file css
  |- assets/
       |- varie immagini
  |- scripts/
       |- futuri file javascript
```

**Comment by marius-leica** [comment]
Ciao Bro! Grazie mille per i feedback! 🤓

Hai ragione, infatti mi chiedevo cosa si poteva fare di diverso. Quella che
ho usato è quella che il tipo usa nel corso. Nn so se magari più avanti nel
corso la cambia, ma nn credo 😅
Decisamente più organizzato come mi hai detto tu...

Il ven 16 apr 2021, 22:45 Leica Florian Robert ***@***.***>
ha scritto:
