### ISSUE TITLE
Utilizzo di tag non necessari

### ISSUE THREAD

**Issue by leicaflorian** [marius-leica/udemy#2]
Ho visto che hai usato in tutte le pagine diversi `[id lt IE...]`. Come mai li hai usati? 
Li hai solo copiati perchè lo hai visto fare o perchè hai capito a cosa servono?

Cmq in realtà non servono più perchè Internet Explorer sotto la versione 11 sono ormai obsoleti e nessuno più se ne preoccupa, quindi non servono più.

![image](https://user-images.githubusercontent.com/28926112/115082727-a2824a80-9f06-11eb-937c-5895ea4c29e3.png)

**Comment by marius-leica** [comment]
In realtà uso l'add-on "boiler" che compila tutta quella roba ma nn so a
cosa serve quella parte... 😢

Il ven 16 apr 2021, 22:54 Leica Florian Robert ***@***.***>
ha scritto:

**Comment by leicaflorian** [comment]
ok, allora lascia stare quell'add-on. Se usi VSCode, ti basta scrivere html:5 e premere tab e ti mette tutto il codice necessario, senza cose inutili.

Questo è tutto quello che ti serve per iniziare.
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>
```

**Comment by marius-leica** [comment]
Ok Bro! Ho visto anche le altre risposte che mi hai mandato. Grazie mille!
🤗

Il dom 18 apr 2021, 11:48 Leica Florian Robert ***@***.***>
ha scritto:

**Comment by leicaflorian** [comment]
Figurati, nessun problema.
Poi quando vai più avanti col corso vediamo insieme qualche aspetto. 😀

Leica Florian Robert
***@***.***
320 294 21 27

Il dom 18 apr 2021, 14:20 marius-leica ***@***.***> ha
scritto:
