### ISSUE TITLE
Utilizzo di <link>

### ISSUE THREAD

**Issue by leicaflorian** [marius-leica/udemy#3]
Sulle pagine hai usato i link di google, con attributo rel="preconnect". 
Attenzione a duplicarli/ triplicarli. Leggi bene le istruzioni su come usarli.

Non limitarti solo a copiare ed incollare le cose, ma cerca di capire il perchè viene usato e sopratutto è importante essere precisi e non fare errori come questi perchè questi in futuro ti potrebbero rallentare molto la pagina e tutto il sito.

![image](https://user-images.githubusercontent.com/28926112/115082999-0efd4980-9f07-11eb-84a4-c4891a41e3d3.png)

**Comment by marius-leica** [comment]
Questi gli ho copiato da Google fonts. Ma nel corso nn ci hanno dato più
dettagli... Quindi nn vanno bene?

Il ven 16 apr 2021, 23:00 Leica Florian Robert ***@***.***>
ha scritto:

**Comment by leicaflorian** [comment]
Si, va bene  copiarli da google fonts, ma attento a non duplicarli inutilmente come hai fatto con "fonts.gstatic.com". quel link basta scriverlo una sola volta.
