### ISSUE TITLE
Qualche problema con alcuni attributi e tag

### ISSUE THREAD

**Issue by leicaflorian** [marius-leica/udemy#4]
Per le tabelle, l'attributo "border" è stato deprecato, quindi non viene più usato in quanto superato. Per settare il bordo anche delle tabelle, usa il css, con la proprietà "border".

Per quanto riguarda i tag, anche `center` è stato deprecato quindi non si usa più. Anche in questo caso usa il css text-align eventualmente sul tag strong.

Ultima cosa, occhio all'immagine e all'attributo width. Occorre specificare l'unità di misura, quindi px o %.

![image](https://user-images.githubusercontent.com/28926112/115083790-3a346880-9f08-11eb-9b78-01a8367e356e.png)

**Comment by marius-leica** [comment]
Ho capito per border e center!
 Ho visto che hai messo la freccia anche su script ma nn mi hai scritto
niente al riguardo... Va bene?

Il ven 16 apr 2021, 23:11 Leica Florian Robert ***@***.***>
ha scritto:

**Comment by leicaflorian** [comment]
Per lo script non ti ho scritto nulla perchè immagino non sei ancora arrivato a lavorare con js. cmq se non lo usi, non scriverlo perchè non serve. Inoltre gli attributi async e defer bisogna capire bene cosa fanno..

Cmq quando arrivi a javascript ne parliamo e ti spiego.
